### PR TITLE
Various GUI and Webserver Changes

### PR DESCRIPTION
**Pull request by TSlaven19**

### CODE REVIEW

**Comment by TSlaven19** [comment]
@Areeb-M , I updated the PathHandler to fix a bug in which it was rendering the SVG as text. This should help out with some HTTP header ambiguity for the various file types the server provides via the PathHandler.

**Comment by Areeb-M** [comment]
Awesome! I'm glad you could make the PathHandler more flexible. That's something I never would have thought to try. Also, we talked about this a little yesterday, but how should we try to represent the different floors? Should we treat them as individual SVGs?

**Comment by Areeb-M** [comment]
Also, I wanted to work a bit on the Main.java file. Do you think you'll still be editing that or am I free to go ahead?

**Comment by TSlaven19** [comment]
> Awesome! I'm glad you could make the PathHandler more flexible. That's something I never would have thought to try. Also, we talked about this a little yesterday, but how should we try to represent the different floors? Should we treat them as individual SVGs?

I think that's the better way to go about it, as opposed to one massive file with all of the floors. We can load them all (layered) and just hide the ones not in use. 

> Do you think you'll still be editing that or am I free to go ahead?

I was thinking of moving to implement fetching the Locations for the drop downs (also, I don't want to steal this if you wanted to do it) but I don't want to step on your toes so I'll hold off and switch gears to working on the other SVGs and CSVs.

**Comment by Areeb-M** [comment]
I think that's a good point to split off for now. I was going to work on the CSV scanner/Map Class so that it can load all the Locations properly. After that's done, you'd be free to implement fetching Locations for the drop downs with some actual Locations to test with.

**Comment by Areeb-M** [comment]
After which, I was going to pivot towards the NavRequestHandler, but we shouldn't have to worry about overlap there.

**Review by Areeb-M — APPROVED** [review]

**Pull request merged**
