### PR TITLE
Location and VerticalTransition Implementation

### PR DESCRIPTION
**Pull request by Areeb-M**
I finished writing the initial versions of these classes. Does anything stick out to y'all? Any documentation I missed, or unclear code that needs to be commented?

### CODE REVIEW

**Comment by Areeb-M** [comment]
Also, thoughts on throwing an error when calculating distance to an unconnected location? I feel like that's more robust than returning -1 or some other impossible value.

**Comment by TSlaven19** [comment]
> Also, thoughts on throwing an error when calculating distance to an unconnected location? I feel like that's more robust than returning -1 or some other impossible value.

I agree with you here.

**Comment by TSlaven19** [comment]
For the constructor in the Location class, I believe you must copy the incoming ArrayList, like how you did for the return value in getConnections().

Can you explain why you used protected variable types in Location over private?

VerticalTransition looks all good to me.

**Comment by Areeb-M** [comment]
> For the constructor in the Location class, I believe you must copy the incoming ArrayList, like how you did for the return value in getConnections().

My reasoning here was so whichever class creates this particular Location object can change the connections to it after initialization. Right now, there's no other way to add connections to a Location with methods in the Location class. I'd like to keep it that way since Location's shouldn't get new connections during runtime.

So instead, this is what I'm envisioning:
```java
ArrayList<Location> room1Connections = new ArrayList<>();
Location room1 = new Location(1, 1, 0, room1Connections);
ArrayList<Location> room2Connections = new ArrayList<>();
Location room2 = new Location(2, 2, 0, room2Connections);

room1Connections.add(room2);
room2Connections.add(room1);
```
This would work for whichever method is creating the Locations, but once that method is over, there shouldn't be any way to change the connections for each Location.


> Can you explain why you used protected variable types in Location over private?

I used protected variables in Location so that they could be accessed in subclasses without the need for accessors. For example, the method `calculateDistance` in VerticalTransition uses `this.z` and `connections`.

**Comment by TSlaven19** [comment]
Thanks for the explanations and reasoning!

I know I'm not one of the reviewers but I would say this looks good to merge.

**Review by SpiralGalaxy87 — APPROVED** [review]

**Pull request merged**
